---
site_name: "AVefi Schema Documentation"
theme:
  name: material
  palette:
    scheme: black
    primary: black
  #logo: images/avefi-logo.png
  features:
    - content.tabs.link
plugins:
  - search
  - mermaid2
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
nav:
  - About: about.md
  - Overview: schema_overview.md
  - Examples: examples.md
site_url: https://av-efi.github.io/av-efi-schema
repo_url: https://github.com/AV-EFI/av-efi-schema
