name: Consistency checks

on: [push]

permissions:
  contents: read

jobs:
  check-derivatives:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Restore global uv cache
        uses: actions/cache/restore@v5
        id: cache-restore
        with:
          path: |
            ~/.cache/uv
            ~/.local/share/uv
            .venv
          key: uv-${{ hashFiles('uv.lock') }}
          restore-keys: |
            uv-

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: false

      - name: Install dependencies
        run: uv sync --group dev --locked

      - name: Build derivatives
        run: uv run doit

      - name: Check for uncommitted changes
        run: |
          [ -z "$(git diff | grep -e '^[-+]' | grep -e '^. *[^#]' \
          | grep -ve '^+++\|^---')" ] || git diff && false
        shell: bash

      - name: Save uv caches
        if: steps.cache-restore.outputs.cache-hit != 'true'
        uses: actions/cache/save@v5
        with:
          path: |
            ~/.cache/uv
            ~/.local/share/uv
            .venv
          key: uv-${{ hashFiles('uv.lock') }}
